#!/usr/bin/env bash

bat=/sys/class/power_supply/BAT0/

# now="$(cat "$bat/charge_now")"
# full="$(cat "$bat/charge_full")"
# per=$(( 100*now/full ))
# per="${per%.*}"
per="$(cat "$bat/capacity")"

# Sometimes the battery may overcharge, reading wrong mAh values
if [ $per -gt 100 ]; then
    per=100
fi

icon() {
    [ $(cat "$bat/status") = Charging ] && echo "􀢋" && exit
    [ $(cat "$bat/status") = Full ] && echo "􀢋" && exit

    if [ "$per" -gt "90" ]; then
        icon="􀛨"
    elif [ "$per" -gt "80" ]; then
        icon="􀺸"
    elif [ "$per" -gt "70" ]; then
        icon="􀺸"
    elif [ "$per" -gt "60" ]; then
        icon="􀺸"
    elif [ "$per" -gt "50" ]; then
        icon="􀺶"
    elif [ "$per" -gt "40" ]; then
        icon="􀺶"
    elif [ "$per" -gt "30" ]; then
        icon="􀛩"
    elif [ "$per" -gt "20" ]; then
        icon="􀛩"
    elif [ "$per" -gt "10" ]; then
        icon="􀛩"
        notify-send -u critical "Battery Low" "Connect charger soon" -h string:x-canonical-private-synchronous:battery-low
    elif [ "$per" -gt "0" ]; then
        icon="􀛪"
        notify-send -u critical "Battery Very Low" "Connect charger now" -h string:x-canonical-private-synchronous:battery-very-low
    else
            echo "􀛪" && exit
    fi

    echo "$per% $icon"
}

percent() {
    echo $per
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit
exit
