#!/bin/sh

CAL_CLIENT="morgen"
CAL_CLIENT_DOMAIN="Morgen"

calendar() {
    LOCK_FILE="$HOME/.cache/eww-calendar.lock"
    EWW_BIN="eww" # We don't actually know where eww is on nix

    run() {
        ${EWW_BIN} -c $HOME/.config/eww/bar open calendar
    }

    # Run eww daemon if not running
    if [[ ! $(pidof eww) ]]; then
        ${EWW_BIN} daemon
        sleep 1
    fi

    # Open widgets
    if [[ ! -f "$LOCK_FILE" ]]; then
        touch "$LOCK_FILE"
        run
    else
        ${EWW_BIN} -c $HOME/.config/eww/bar close calendar
        rm "$LOCK_FILE"
    fi
}

gcalendar() {
    if [ -n "$(pidof $CAL_CLIENT)" ]; then
        cal_workspace=$(hyprctl clients -j | \
                        jq ".[] | {(.class): .workspace.id}" | \
                        grep "${CAL_CLIENT_DOMAIN:-$CAL_CLIENT}" | \
                        awk '{print $2}')

        hyprctl dispatch workspace "$cal_workspace"
    else
        ${CAL_CLIENT}
    fi
}

if [ "$1" = "launcher" ]; then
    $HOME/.local/bin/launcher
elif [ "$1" = "wifi" ]; then
    # Refresh station list
    $HOME/.local/bin/wifimenu
elif [ "$1" = "audio" ]; then
    pavucontrol
elif [ "$1" = "calendar" ]; then
    gcalendar
fi
