format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$golang\
$haskell\
$ocaml\
$python\
$rust\
$sudo\
$cmd_duration\
$nix_shell\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

[rlang]
disabled = true

[nix_shell]
impure_msg='nix develop'
format='via [$symbol$state]($style) '
