#!/usr/bin/env bash

iDIR="$HOME/.config/hypr/mako/icons"

# Get brightness
get_backlight() {
	LIGHT=$(printf "%.0f\n" $(light))
	echo "${LIGHT}%"
}

# Get icons
get_icon() {
	backlight="$(get_backlight)"
	current="${backlight%%%}"
	if [[ ("$current" -ge "0") && ("$current" -le "20") ]]; then
		icon="$iDIR/brightness-20.png"
	elif [[ ("$current" -ge "20") && ("$current" -le "40") ]]; then
		icon="$iDIR/brightness-40.png"
	elif [[ ("$current" -ge "40") && ("$current" -le "60") ]]; then
		icon="$iDIR/brightness-60.png"
	elif [[ ("$current" -ge "60") && ("$current" -le "80") ]]; then
		icon="$iDIR/brightness-80.png"
	elif [[ ("$current" -ge "80") && ("$current" -le "100") ]]; then
		icon="$iDIR/brightness-100.png"
	fi
}

# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Brightness : $(get_backlight)"
}

# Increase brightness
inc_backlight() {
    amt=5

    if [ -n "$1" ]; then
        amt=$1
    fi

	light -A "$amt" && get_icon && notify_user
}

inc_keyb_backlight() {
    amt=5

    if [ -n "$1" ]; then
        amt=$1
    fi

	light -s sysfs/leds/smc::kbd_backlight -A "$amt"
}

# Decrease brightness
dec_backlight() {
    amt=5

    if [ -n "$1" ]; then
        amt=$1
    fi

	light -U "$amt" && get_icon && notify_user
}

dec_keyb_backlight() {
    amt=5

    if [ -n "$1" ]; then
        amt=$1
    fi

	light -s sysfs/leds/smc::kbd_backlight -U "$amt"
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_backlight
elif [[ "$1" == "--inc" ]]; then
	inc_backlight "$2"
elif [[ "$1" == "--dec" ]]; then
	dec_backlight "$2"
elif [[ "$1" == "--kinc" ]]; then
	inc_keyb_backlight "$2"
elif [[ "$1" == "--kdec" ]]; then
	dec_keyb_backlight "$2"
else
	get_backlight
fi
