#!/bin/bash
CONFIG="$HOME/.config/hypr/wofi/config"
STYLE="$HOME/.config/hypr/wofi/style.css"
COLORS="$HOME/.config/hypr/wofi/colors"

if [[ ! $(pidof rofi) ]]; then
	rofi -show run
else
	pkill rofi
fi
