#!/bin/bash

shutdown() {
    OK=$(yad --form --text="Are you sure you want to shut down?" && echo "ok")

    if [ -n "$OK" ]; then
        shutdown
    fi
}

case "$1" in
    "shutdown") shutdown ;;
esac
